name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Download dependencies
      run: ./gradlew build --stacktrace

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Check Dir for find APK
      run: |
          ls ./ -a
          tree ./app/build/outputs/apk/release

    - name: Upload APK
      uses: actions/upload-artifact@v4.4.0
      with:
        name: LADB.apk
        path: ./app/build/outputs/apk/release/app-release.apk
