name: unsigned Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger the workflow for version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Cache Gradle packages
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}

    - name: Download dependencies
      run: ./gradlew build --stacktrace

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Check Dir for find APK
      run: |
          ls ./ -a
          tree ./app/build/outputs/apk/release

    - name: Upload APK
      uses: actions/upload-artifact@v4.4.0
      with:
        name: LADB_unsigned.apk
        path: ./app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.run_number }}${{ github.workflow_sha }}
        release_name: unsigned APK
        body: 'Release of version ${{ github.ref }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app/build/outputs/apk/release/app-release-unsigned.apk
        asset_name: LADB_unsigned.apk
        asset_content_type: application/vnd.android.package-archive
